### ISSUE TITLE
ERR during installation

### ISSUE THREAD

**Issue by snikumbh** [hms-dbmi/higlass-website#30]
Hi,
I got the following error when running `npm install` from higlass-website.

> binding.target.mk:115: recipe for target 'Release/obj.target/binding/src/binding.o' failed
make: *** [Release/obj.target/binding/src/binding.o] Error 1
make: Leaving directory '/opt/estrella/higlass-website/node_modules/node-sass/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/opt/estrella/higlass-website/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:225:12)
gyp ERR! System Linux 4.9.76.1.amd64-smp
gyp ERR! command "/opt/estrella/.linuxbrew/Cellar/node/10.0.0/bin/node" "/opt/estrella/higlass-website/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /opt/estrella/higlass-website/node_modules/node-sass
gyp ERR! node -v v10.0.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
Build failed with error code: 1
npm WARN eslint-config-airbnb-base@11.3.2 requires a peer of eslint-plugin-import@^2.7.0 but none is installed. You must install peer dependencies yourself.
npm WARN higlass@0.8.2 requires a peer of react@^15.5.4 but none is installed. You must install peer dependencies yourself.
npm WARN higlass@0.8.2 requires a peer of react-dom@^15.5.4 but none is installed. You must install peer dependencies yourself.
npm WARN react-autocomplete@1.4.0 requires a peer of react@^0.14.7 || ^15.0.0-0 but none is installed. You must install peer dependencies yourself.
npm WARN react-autocomplete@1.4.0 requires a peer of react-dom@^0.14.7 || ^15.0.0-0 but none is installed. You must install peer dependencies yourself.
npm WARN react-contextmenu@2.8.0 requires a peer of react@^0.14.0 || ^15.0.0 || ^16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-contextmenu@2.8.0 requires a peer of react-dom@^0.14.0 || ^15.0.0 || ^16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-dimensions@1.3.1 requires a peer of react@^0.14.0 || ^15.0.0 || ^16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-dimensions@1.3.1 requires a peer of react-dom@^0.14.0 || ^15.0.0 || ^16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-grid-layout@0.13.9 requires a peer of react@^0.14.3 || ^15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-grid-layout@0.13.9 requires a peer of react-dom@^0.14.3 || ^15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-resizable@1.7.5 requires a peer of react@0.14.x || 15.x || 16.x but none is installed. You must install peer dependencies yourself.
npm WARN react-resizable@1.7.5 requires a peer of react-dom@0.14.x || 15.x || 16.x but none is installed. You must install peer dependencies yourself.
npm WARN react-sortable-hoc@0.1.1 requires a peer of react@^0.14.0 || ^15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-sortable-hoc@0.1.1 requires a peer of react-dom@^0.14.0 || ^15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.5.3 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@4.5.3 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /opt/estrella/.npm/_logs/2018-04-27T10_56_55_188Z-debug.log

I can share the debug.log file if required. Appreciate any help in resolving this.

I am working on debian, and am using linuxbrew. I have already installed higlass-server and higlass successfully. I am attempting individual installations of the components since, unfortunately, I can't have docker images running on our servers.
Thanks.
-Sarvesh

**Comment by snikumbh** [comment]
Issue reported at https://github.com/sass/node-sass/issues/428 seems to be similar/same to what I am encountering. I will try some options suggested there and update if it works.

**Comment by snikumbh** [comment]
Ok, so I installed node-sass separately, and had to take care of the peer dependencies. (Never used node.js or npm before; new to the terminology.) 

> npm WARN eslint-config-airbnb-base@11.3.2 requires a peer of eslint-plugin-import@^2.7.0 but none is installed. You must install peer dependencies yourself.
npm WARN higlass@0.8.2 requires a peer of react@^15.5.4 but none is installed. You must install peer dependencies yourself.

And, then did `npm start` to get the following error:

> npm start

> higlass-website@0.6.18 start /opt/estrella/higlass-website
> gulp serve
[14:39:52] Requiring external module babel-register
gulp[7654]: ../src/node_contextify.cc:631:static void node::contextify::ContextifyScript::New(const v8::FunctionCallbackInfo<v8::Value>&): Assertion `args[1]->IsString()` failed.
 1: node::Abort() [gulp]
 2: 0x55de0c28650d [gulp]
 3: node::contextify::ContextifyScript::New(v8::FunctionCallbackInfo<v8::Value> const&) [gulp]
 4: v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo*) [gulp]
 5: 0x55de0c4dce92 [gulp]
 6: v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*) [gulp]
 7: 0x38eaa7c8427d
Aborted
npm ERR! code ELIFECYCLE
npm ERR! errno 134
npm ERR! higlass-website@0.6.18 start: `gulp serve`
npm ERR! Exit status 134
npm ERR! 
npm ERR! Failed at the higlass-website@0.6.18 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /opt/estrella/.npm/_logs/2018-04-27T12_39_53_905Z-debug.log

Any idea? 
Thanks.

**Comment by snikumbh** [comment]
Resolved the above `gulp serve` issue by following instructions at https://github.com/gulpjs/gulp/issues/2162, and finally got the higlass-website running!
